Tento notebook procvičuje práci s Jupyter Notebooky, numpy a matplotlib.

Pythagorova věta:

$$ c = \sqrt{a^2 + b^2} $$

Inline použití: pro $a = 3$ a $b = 4$ vyjde $c = 5$.

## Obrázek

![Logo Pythonu](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)

In [8]:
a = 3
b = 4
c = (a**2 + b**2) ** 0.5
c

5.0

In [34]:
import numpy as np
data = np.load("pacienti.npy")
data

array([[129.6,  78.2,  93. ],
       [109.4,  73.2,  72. ],
       [136.3,  92.2,  61. ],
       [139.1,  78.5,  89. ],
       [ 95.7,  75.7,  80. ],
       [105.5,  76.5,  83. ],
       [126.9,  85.3,  58. ],
       [120.3,  83.7,  67. ],
       [124.7,  84.1,  86. ],
       [112.2,  84.3,  89. ],
       [138.2, 101.4,  72. ],
       [136.7,  75.9,  87. ],
       [126. ,  74.9,  89. ],
       [141.9,  71.9,  70. ],
       [132. ,  86.2,  91. ],
       [112.1,  91.3,  66. ],
       [130.5,  78.9,  64. ],
       [110.6,  71.6,  82. ],
       [138.2,  71.8,  81. ],
       [124.3,  86.5,  60. ]])

In [35]:
print(data[:5])

[[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]]


In [41]:
pru = data.mean(axis=0)
odch = data.std(axis=0)
odch, pru

(array([12.72807527,  7.73869983, 11.28273017]),
 array([124.51 ,  81.105,  77.   ]))

In [47]:
a1 = data[:, 0] >= 140
a2 = data[a1]
if len(a2) > 0:
    a3 = np.mean(a2[:, 0])
print(a3)

141.9


In [49]:
b1 = data[:, 0] - data[:, 1]
b2 = np.column_stack((data, b1))
print(b2.shape)
print(b2[:3])


(20, 4)
[[129.6  78.2  93.   51.4]
 [109.4  73.2  72.   36.2]
 [136.3  92.2  61.   44.1]]


In [50]:
c1 = np.argmax(data[:, 2])
c2 = data[c1]
print(c1)
print(c2)

0
[129.6  78.2  93. ]
